// <auto-generated />
using System;
using CraftDailyCorner.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CraftDailyCorner.Migrations
{
    [DbContext(typeof(CraftDailyCornerContext))]
    partial class CraftDailyCornerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CraftDailyCorner.Models.AutoReplyTemplate", b =>
                {
                    b.Property<int>("TemplateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("TriggerType")
                        .HasColumnType("tinyint");

                    b.HasKey("TemplateID");

                    b.HasIndex("CreatorID");

                    b.ToTable("AutoReplyTemplate");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Cart", b =>
                {
                    b.Property<int>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartID"));

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CartID");

                    b.HasIndex("MemberID");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CartItem", b =>
                {
                    b.Property<int>("CartID")
                        .HasColumnType("int");

                    b.Property<string>("ProductID")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.HasKey("CartID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorApplication", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationID"));

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<string>("PortfolioSampleUrl")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nchar(40)");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedBy")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("ApplicationID");

                    b.HasIndex("MemberID");

                    b.HasIndex("ReviewedBy");

                    b.ToTable("CreatorApplication");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorPost", b =>
                {
                    b.Property<string>("PostID")
                        .HasMaxLength(36)
                        .HasColumnType("nchar(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nchar(40)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Visibility")
                        .HasColumnType("tinyint");

                    b.HasKey("PostID");

                    b.HasIndex("CreatorID");

                    b.ToTable("CreatorPost");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorProfile", b =>
                {
                    b.Property<string>("CreatorID")
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("BankCode")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("CreatorID");

                    b.HasIndex("MemberID")
                        .IsUnique();

                    b.ToTable("CreatorProfile");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.FavoriteProduct", b =>
                {
                    b.Property<string>("MemberID")
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<string>("ProductID")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("FavoriteProduct");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.FollowCreator", b =>
                {
                    b.Property<string>("MemberID")
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<string>("CreatorID")
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberID", "CreatorID");

                    b.HasIndex("CreatorID");

                    b.ToTable("FollowCreator");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.HomepageBanner", b =>
                {
                    b.Property<int>("BannerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BannerID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nchar(40)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BannerID");

                    b.HasIndex("CreatedBy");

                    b.ToTable("HomepageBanner");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryID"));

                    b.Property<short>("AlertQty")
                        .HasColumnType("smallint");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<short>("StockQty")
                        .HasColumnType("smallint");

                    b.HasKey("InventoryID");

                    b.HasIndex("ProductID")
                        .IsUnique();

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.InventoryAlert", b =>
                {
                    b.Property<int>("AlertID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertID"));

                    b.Property<int>("InventoryID")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AlertID");

                    b.HasIndex("InventoryID");

                    b.ToTable("InventoryAlert");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Member", b =>
                {
                    b.Property<string>("MemberID")
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nchar(40)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("MemberID");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.MemberRole", b =>
                {
                    b.Property<string>("MemberID")
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<string>("RoleID")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("MemberRole");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.MemberRoleHistory", b =>
                {
                    b.Property<long>("MemberRoleHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MemberRoleHistoryID"));

                    b.Property<byte>("Action")
                        .HasColumnType("tinyint");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<DateTime>("OperatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("OperatedBy")
                        .HasColumnType("tinyint");

                    b.Property<string>("OperatorMemberID")
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<string>("RoleID")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)");

                    b.HasKey("MemberRoleHistoryID");

                    b.HasIndex("OperatorMemberID");

                    b.HasIndex("RoleID");

                    b.ToTable("MemberRoleHistory");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Message", b =>
                {
                    b.Property<long>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SenderID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<int>("ThreadID")
                        .HasColumnType("int");

                    b.HasKey("MessageID");

                    b.HasIndex("SenderID");

                    b.HasIndex("ThreadID");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.MessageThread", b =>
                {
                    b.Property<int>("ThreadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThreadID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<string>("CreatorProfileCreatorID")
                        .HasColumnType("nchar(6)");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.HasKey("ThreadID");

                    b.HasIndex("CreatorID");

                    b.HasIndex("CreatorProfileCreatorID");

                    b.ToTable("MessageThread");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.NotificationEvent", b =>
                {
                    b.Property<long>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<byte>("NotificationType")
                        .HasColumnType("tinyint");

                    b.HasKey("EventID");

                    b.HasIndex("MemberID");

                    b.ToTable("NotificationEvent");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.NotificationPreference", b =>
                {
                    b.Property<long>("PreferenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PreferenceID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<byte>("NotificationType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PreferenceID");

                    b.HasIndex("MemberID");

                    b.ToTable("NotificationPreference");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Order", b =>
                {
                    b.Property<string>("OrderID")
                        .HasMaxLength(12)
                        .HasColumnType("nchar(12)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("money");

                    b.HasKey("OrderID");

                    b.HasIndex("MemberID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.OrderDetail", b =>
                {
                    b.Property<string>("OrderID")
                        .HasMaxLength(12)
                        .HasColumnType("nchar(12)");

                    b.Property<string>("ProductID")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<decimal>("PriceSnapshot")
                        .HasColumnType("money");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<byte>("AttemptNo")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GatewayTradeNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nchar(12)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("PaymentID");

                    b.HasIndex("OrderID");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PlatformAnnouncement", b =>
                {
                    b.Property<int>("AnnouncementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nchar(8)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AnnouncementID");

                    b.HasIndex("CreatedBy");

                    b.ToTable("PlatformAnnouncement");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PlatformSetting", b =>
                {
                    b.Property<int>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingID"));

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.HasKey("SettingID");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("PlatformSetting");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Portfolio", b =>
                {
                    b.Property<string>("PortfolioID")
                        .HasMaxLength(36)
                        .HasColumnType("nchar(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PortfolioID");

                    b.HasIndex("CreatorID");

                    b.ToTable("Portfolio");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PortfolioItem", b =>
                {
                    b.Property<string>("ItemID")
                        .HasMaxLength(36)
                        .HasColumnType("nchar(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nchar(40)");

                    b.Property<string>("PortfolioID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nchar(36)");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ItemID");

                    b.HasIndex("PortfolioID");

                    b.ToTable("PortfolioItem");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PostComment", b =>
                {
                    b.Property<string>("CommentID")
                        .HasMaxLength(36)
                        .HasColumnType("nchar(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<string>("PostID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nchar(36)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("CommentID");

                    b.HasIndex("MemberID");

                    b.HasIndex("PostID");

                    b.ToTable("PostComment");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Privacy", b =>
                {
                    b.Property<string>("MemberID")
                        .HasColumnType("nchar(8)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasColumnType("nchar(10)");

                    b.HasKey("MemberID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Privacy");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Product", b =>
                {
                    b.Property<string>("ProductID")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("ProductID");

                    b.HasIndex("CreatorID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ProductCategory", b =>
                {
                    b.Property<string>("ProductID")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.HasKey("ProductID", "CategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("ProductCategory");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ProductImage", b =>
                {
                    b.Property<long>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImageID"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nchar(40)");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("ImageID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductImage");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ProductReview", b =>
                {
                    b.Property<long>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReviewID"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.HasKey("ReviewID");

                    b.HasIndex("MemberID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductReview");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ProductTag", b =>
                {
                    b.Property<string>("ProductID")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.HasKey("ProductID", "TagID");

                    b.HasIndex("TagID");

                    b.ToTable("ProductTag");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Role", b =>
                {
                    b.Property<string>("RoleID")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("RoleID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Shipment", b =>
                {
                    b.Property<int>("ShipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipmentID"));

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nchar(12)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("TrackingNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ShipmentID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.ToTable("Shipment");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Tag", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagID"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TagID");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.AutoReplyTemplate", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.CreatorProfile", "CreatorProfile")
                        .WithMany("AutoReplyTemplate")
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorProfile");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Cart", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("Cart")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CartItem", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Cart", "Cart")
                        .WithMany("CartItem")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Product", "Product")
                        .WithMany("CartItem")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorApplication", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Reviewer")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("CreatorApplication")
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorPost", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.CreatorProfile", "CreatorProfile")
                        .WithMany("CreatorPost")
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorProfile");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorProfile", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithOne("CreatorProfile")
                        .HasForeignKey("CraftDailyCorner.Models.CreatorProfile", "MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.FavoriteProduct", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("FavoriteProduct")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Product", "Product")
                        .WithMany("FavoriteProduct")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.FollowCreator", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.CreatorProfile", "CreatorProfile")
                        .WithMany("FollowCreator")
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("FollowCreator")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorProfile");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.HomepageBanner", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("HomepageBanner")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Inventory", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("CraftDailyCorner.Models.Inventory", "ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.InventoryAlert", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Inventory", "Inventory")
                        .WithMany("InventoryAlert")
                        .HasForeignKey("InventoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.MemberRole", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("MemberRole")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Role", "Role")
                        .WithMany("MemberRole")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.MemberRoleHistory", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("MemberRoleHistory")
                        .HasForeignKey("OperatorMemberID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CraftDailyCorner.Models.Role", "Role")
                        .WithMany("MemberRoleHistory")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Message", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("Message")
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.MessageThread", "MessageThread")
                        .WithMany("Message")
                        .HasForeignKey("ThreadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("MessageThread");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.MessageThread", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("MessageThread")
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.CreatorProfile", null)
                        .WithMany("MessageThread")
                        .HasForeignKey("CreatorProfileCreatorID");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.NotificationEvent", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("NotificationEvent")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.NotificationPreference", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("NotificationPreference")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Order", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("Order")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.OrderDetail", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Order", "Order")
                        .WithMany("OrderDetail")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Product", "Product")
                        .WithMany("OrderDetail")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Payment", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Order", "Order")
                        .WithMany("Payment")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PlatformAnnouncement", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("PlatformAnnouncement")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PlatformSetting", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("PlatformSetting")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Portfolio", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.CreatorProfile", "CreatorProfile")
                        .WithMany("Portfolio")
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorProfile");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PortfolioItem", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Portfolio", "Portfolio")
                        .WithMany("PortfolioItem")
                        .HasForeignKey("PortfolioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PostComment", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("PostComment")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.CreatorPost", "CreatorPost")
                        .WithMany("PostComment")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorPost");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Privacy", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithOne("Privacy")
                        .HasForeignKey("CraftDailyCorner.Models.Privacy", "MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Product", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.CreatorProfile", "CreatorProfile")
                        .WithMany("Product")
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatorProfile");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ProductCategory", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Category", "Category")
                        .WithMany("ProductCategory")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Product", "Product")
                        .WithMany("ProductCategory")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ProductImage", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Product", "Product")
                        .WithMany("ProductImage")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ProductReview", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("ProductReview")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Product", "Product")
                        .WithMany("ProductReview")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ProductTag", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Product", "Product")
                        .WithMany("ProductTag")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Tag", "Tag")
                        .WithMany("ProductTag")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Shipment", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Order", "Order")
                        .WithOne("Shipment")
                        .HasForeignKey("CraftDailyCorner.Models.Shipment", "OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Cart", b =>
                {
                    b.Navigation("CartItem");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Category", b =>
                {
                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorPost", b =>
                {
                    b.Navigation("PostComment");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorProfile", b =>
                {
                    b.Navigation("AutoReplyTemplate");

                    b.Navigation("CreatorPost");

                    b.Navigation("FollowCreator");

                    b.Navigation("MessageThread");

                    b.Navigation("Portfolio");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Inventory", b =>
                {
                    b.Navigation("InventoryAlert");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Member", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("CreatorApplication");

                    b.Navigation("CreatorProfile");

                    b.Navigation("FavoriteProduct");

                    b.Navigation("FollowCreator");

                    b.Navigation("HomepageBanner");

                    b.Navigation("MemberRole");

                    b.Navigation("MemberRoleHistory");

                    b.Navigation("Message");

                    b.Navigation("MessageThread");

                    b.Navigation("NotificationEvent");

                    b.Navigation("NotificationPreference");

                    b.Navigation("Order");

                    b.Navigation("PlatformAnnouncement");

                    b.Navigation("PlatformSetting");

                    b.Navigation("PostComment");

                    b.Navigation("Privacy");

                    b.Navigation("ProductReview");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.MessageThread", b =>
                {
                    b.Navigation("Message");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Order", b =>
                {
                    b.Navigation("OrderDetail");

                    b.Navigation("Payment");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Portfolio", b =>
                {
                    b.Navigation("PortfolioItem");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Product", b =>
                {
                    b.Navigation("CartItem");

                    b.Navigation("FavoriteProduct");

                    b.Navigation("Inventory");

                    b.Navigation("OrderDetail");

                    b.Navigation("ProductCategory");

                    b.Navigation("ProductImage");

                    b.Navigation("ProductReview");

                    b.Navigation("ProductTag");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Role", b =>
                {
                    b.Navigation("MemberRole");

                    b.Navigation("MemberRoleHistory");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Tag", b =>
                {
                    b.Navigation("ProductTag");
                });
#pragma warning restore 612, 618
        }
    }
}
