// <auto-generated />
using System;
using CraftDailyCorner.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CraftDailyCorner.Migrations
{
    [DbContext(typeof(CraftDailyCornerContext))]
    partial class CraftDailyCornerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CraftDailyCorner.Models.AutoReplyTemplate", b =>
                {
                    b.Property<int>("TemplateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("TriggerType")
                        .HasColumnType("tinyint");

                    b.HasKey("TemplateID");

                    b.HasIndex("CreatorID");

                    b.ToTable("AutoReplyTemplates");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Cart", b =>
                {
                    b.Property<int>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.HasKey("CartID");

                    b.HasIndex("MemberID");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CartItem", b =>
                {
                    b.Property<int>("CartID")
                        .HasColumnType("int");

                    b.Property<string>("ProductID")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CartID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentCategoryID")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.HasIndex("ParentCategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorApplication", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationID"));

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<string>("PortfolioSampleUrl")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nchar(40)");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedBy")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.HasKey("ApplicationID");

                    b.HasIndex("MemberID");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("StatusID");

                    b.ToTable("CreatorApplications");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorApplicationStatus", b =>
                {
                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusID");

                    b.HasIndex("StatusCode")
                        .IsUnique();

                    b.ToTable("CreatorApplicationStatuses");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorPost", b =>
                {
                    b.Property<string>("PostID")
                        .HasMaxLength(36)
                        .HasColumnType("nchar(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nchar(40)");

                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Visibility")
                        .HasColumnType("tinyint");

                    b.HasKey("PostID");

                    b.HasIndex("CreatorID");

                    b.HasIndex("StatusID");

                    b.ToTable("CreatorPosts");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorPostStatus", b =>
                {
                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusID");

                    b.HasIndex("StatusCode")
                        .IsUnique();

                    b.ToTable("CreatorPostStatuses");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorProfile", b =>
                {
                    b.Property<string>("CreatorID")
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("BankCode")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.HasKey("CreatorID");

                    b.HasIndex("MemberID")
                        .IsUnique();

                    b.HasIndex("StatusID");

                    b.ToTable("CreatorProfiles");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorProfileStatus", b =>
                {
                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusID");

                    b.HasIndex("StatusCode")
                        .IsUnique();

                    b.ToTable("CreatorProfileStatuses");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.FavoriteProduct", b =>
                {
                    b.Property<string>("MemberID")
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<string>("ProductID")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberID", "ProductID");

                    b.HasIndex("ProductID");

                    b.HasIndex("MemberID", "ProductID")
                        .IsUnique();

                    b.ToTable("FavoriteProducts");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.FollowCreator", b =>
                {
                    b.Property<string>("MemberID")
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<string>("CreatorID")
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberID", "CreatorID");

                    b.HasIndex("CreatorID");

                    b.HasIndex("MemberID", "CreatorID")
                        .IsUnique();

                    b.ToTable("FollowCreators");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.HomepageBanner", b =>
                {
                    b.Property<int>("BannerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BannerID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nchar(40)");

                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BannerID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("StatusID");

                    b.ToTable("HomepageBanners");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.HomepageBannerStatus", b =>
                {
                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusID");

                    b.HasIndex("StatusCode")
                        .IsUnique();

                    b.ToTable("HomepageBannerStatuses");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryID"));

                    b.Property<int>("AlertQty")
                        .HasColumnType("int");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<int>("StockQty")
                        .HasColumnType("int");

                    b.HasKey("InventoryID");

                    b.HasIndex("ProductID")
                        .IsUnique();

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.InventoryAlert", b =>
                {
                    b.Property<int>("AlertID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertID"));

                    b.Property<int>("InventoryID")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AlertID");

                    b.HasIndex("InventoryID");

                    b.ToTable("InventoryAlerts");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Member", b =>
                {
                    b.Property<string>("MemberID")
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.HasKey("MemberID");

                    b.HasIndex("StatusID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.MemberRole", b =>
                {
                    b.Property<string>("MemberID")
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<string>("RoleID")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("MemberRoles");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.MemberRoleHistory", b =>
                {
                    b.Property<long>("MemberRoleHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MemberRoleHistoryID"));

                    b.Property<byte>("Action")
                        .HasColumnType("tinyint");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<DateTime>("OperatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("OperatedBy")
                        .HasColumnType("tinyint");

                    b.Property<string>("OperatorMemberID")
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<string>("RoleID")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)");

                    b.HasKey("MemberRoleHistoryID");

                    b.HasIndex("MemberID");

                    b.HasIndex("OperatorMemberID");

                    b.HasIndex("RoleID");

                    b.ToTable("MemberRoleHistories");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.MemberStatus", b =>
                {
                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusID");

                    b.HasIndex("StatusCode")
                        .IsUnique();

                    b.ToTable("MemberStatuses");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Message", b =>
                {
                    b.Property<long>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SenderID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<int>("ThreadID")
                        .HasColumnType("int");

                    b.HasKey("MessageID");

                    b.HasIndex("SenderID");

                    b.HasIndex("ThreadID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.MessageThread", b =>
                {
                    b.Property<int>("ThreadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThreadID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(6)");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.HasKey("ThreadID");

                    b.HasIndex("CreatorID");

                    b.HasIndex("MemberID");

                    b.ToTable("MessageThreads");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.NotificationEvent", b =>
                {
                    b.Property<long>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<byte>("NotificationType")
                        .HasColumnType("tinyint");

                    b.HasKey("EventID");

                    b.HasIndex("MemberID");

                    b.ToTable("NotificationEvents");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.NotificationPreference", b =>
                {
                    b.Property<long>("PreferenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PreferenceID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<byte>("NotificationType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PreferenceID");

                    b.HasIndex("MemberID");

                    b.ToTable("NotificationPreferences");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Order", b =>
                {
                    b.Property<string>("OrderID")
                        .HasMaxLength(12)
                        .HasColumnType("nchar(12)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("money");

                    b.HasKey("OrderID");

                    b.HasIndex("MemberID");

                    b.HasIndex("StatusID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.OrderDetail", b =>
                {
                    b.Property<string>("OrderID")
                        .HasMaxLength(12)
                        .HasColumnType("nchar(12)");

                    b.Property<string>("ProductID")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<decimal>("PriceSnapshot")
                        .HasColumnType("money");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.OrderStatus", b =>
                {
                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusID");

                    b.HasIndex("StatusCode")
                        .IsUnique();

                    b.ToTable("OrderStatuses");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PasswordResetToken", b =>
                {
                    b.Property<long>("PasswordResetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PasswordResetId"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasColumnType("nchar(8)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.HasKey("PasswordResetId");

                    b.HasIndex("MemberID");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<byte>("AttemptNo")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GatewayTradeNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("MethodID")
                        .HasColumnType("tinyint");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nchar(12)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.HasKey("PaymentID");

                    b.HasIndex("MethodID");

                    b.HasIndex("OrderID");

                    b.HasIndex("StatusID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PaymentMethod", b =>
                {
                    b.Property<byte>("MethodID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MethodCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MethodID");

                    b.HasIndex("MethodCode")
                        .IsUnique();

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PaymentStatus", b =>
                {
                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusID");

                    b.HasIndex("StatusCode")
                        .IsUnique();

                    b.ToTable("PaymentStatuses");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PlatformAnnouncement", b =>
                {
                    b.Property<int>("AnnouncementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nchar(8)");

                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AnnouncementID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("StatusID");

                    b.ToTable("PlatformAnnouncements");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PlatformAnnouncementStatus", b =>
                {
                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusID");

                    b.HasIndex("StatusCode")
                        .IsUnique();

                    b.ToTable("PlatformAnnouncementStatuses");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PlatformSetting", b =>
                {
                    b.Property<int>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingID"));

                    b.Property<byte>("CategoryID")
                        .HasColumnType("tinyint");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.HasKey("SettingID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("PlatformSettings");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PlatformSettingCategory", b =>
                {
                    b.Property<byte>("CategoryID")
                        .HasColumnType("tinyint");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryCode")
                        .IsUnique();

                    b.ToTable("PlatformSettingCategories");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Portfolio", b =>
                {
                    b.Property<string>("PortfolioID")
                        .HasMaxLength(36)
                        .HasColumnType("nchar(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PortfolioID");

                    b.HasIndex("CreatorID");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PortfolioItem", b =>
                {
                    b.Property<string>("ItemID")
                        .HasMaxLength(36)
                        .HasColumnType("nchar(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nchar(40)");

                    b.Property<string>("PortfolioID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nchar(36)");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ItemID");

                    b.HasIndex("PortfolioID");

                    b.ToTable("PortfolioItems");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PostComment", b =>
                {
                    b.Property<string>("CommentID")
                        .HasMaxLength(36)
                        .HasColumnType("nchar(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<string>("PostID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nchar(36)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("CommentID");

                    b.HasIndex("MemberID");

                    b.HasIndex("PostID");

                    b.ToTable("PostComments");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PostCommentReport", b =>
                {
                    b.Property<long>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReportID"));

                    b.Property<string>("CommentID")
                        .IsRequired()
                        .HasColumnType("nchar(36)");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasColumnType("nchar(8)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.HasKey("ReportID");

                    b.HasIndex("CommentID");

                    b.HasIndex("MemberID");

                    b.HasIndex("StatusID");

                    b.ToTable("PostCommentReports");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PostCommentReportStatus", b =>
                {
                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusID");

                    b.HasIndex("StatusCode")
                        .IsUnique();

                    b.ToTable("PostCommentReportStatuses");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Privacy", b =>
                {
                    b.Property<string>("MemberID")
                        .HasColumnType("nchar(8)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasColumnType("nchar(10)");

                    b.HasKey("MemberID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasFilter("[Phone] IS NOT NULL");

                    b.ToTable("Privacies");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Product", b =>
                {
                    b.Property<string>("ProductID")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.HasKey("ProductID");

                    b.HasIndex("CreatorID");

                    b.HasIndex("StatusID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ProductCategory", b =>
                {
                    b.Property<string>("ProductID")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.HasKey("ProductID", "CategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ProductImage", b =>
                {
                    b.Property<long>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImageID"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nchar(40)");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("tinyint");

                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.HasKey("ImageID");

                    b.HasIndex("ProductID");

                    b.HasIndex("StatusID");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ProductImageStatus", b =>
                {
                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusID");

                    b.HasIndex("StatusCode")
                        .IsUnique();

                    b.ToTable("ProductImageStatuses");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ProductReview", b =>
                {
                    b.Property<long>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReviewID"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.HasKey("ReviewID");

                    b.HasIndex("MemberID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ProductStatus", b =>
                {
                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusID");

                    b.HasIndex("StatusCode")
                        .IsUnique();

                    b.ToTable("ProductStatuses");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ProductTag", b =>
                {
                    b.Property<string>("ProductID")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.HasKey("ProductID", "TagID");

                    b.HasIndex("TagID");

                    b.ToTable("ProductTags");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Role", b =>
                {
                    b.Property<string>("RoleID")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Shipment", b =>
                {
                    b.Property<int>("ShipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipmentID"));

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nchar(12)");

                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.Property<string>("TrackingNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ShipmentID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.HasIndex("StatusID");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ShipmentStatus", b =>
                {
                    b.Property<byte>("StatusID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusID");

                    b.HasIndex("StatusCode")
                        .IsUnique();

                    b.ToTable("ShipmentStatuses");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Tag", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TagID");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.AutoReplyTemplate", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.CreatorProfile", "CreatorProfile")
                        .WithMany("AutoReplyTemplates")
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorProfile");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Cart", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("Carts")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CartItem", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Category", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorApplication", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("CreatorApplications")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Member", "Reviewer")
                        .WithMany("ReviewedCreatorApplications")
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.CreatorApplicationStatus", "CreatorApplicationStatus")
                        .WithMany("CreatorApplications")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatorApplicationStatus");

                    b.Navigation("Member");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorPost", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.CreatorProfile", "CreatorProfile")
                        .WithMany("CreatorPosts")
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.CreatorPostStatus", "CreatorPostStatus")
                        .WithMany("CreatorPosts")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatorPostStatus");

                    b.Navigation("CreatorProfile");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorProfile", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithOne("CreatorProfile")
                        .HasForeignKey("CraftDailyCorner.Models.CreatorProfile", "MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.CreatorProfileStatus", "CreatorProfileStatus")
                        .WithMany("CreatorProfiles")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatorProfileStatus");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.FavoriteProduct", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("FavoriteProducts")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Product", "Product")
                        .WithMany("FavoriteProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.FollowCreator", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.CreatorProfile", "CreatorProfile")
                        .WithMany("FollowCreators")
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("FollowCreators")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatorProfile");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.HomepageBanner", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("HomepageBanners")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.HomepageBannerStatus", "HomepageBannerStatus")
                        .WithMany("HomepageBanners")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HomepageBannerStatus");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Inventory", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("CraftDailyCorner.Models.Inventory", "ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.InventoryAlert", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Inventory", "Inventory")
                        .WithMany("InventoryAlerts")
                        .HasForeignKey("InventoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Member", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.MemberStatus", "MemberStatus")
                        .WithMany("Members")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MemberStatus");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.MemberRole", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("MemberRoles")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Role", "Role")
                        .WithMany("MemberRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.MemberRoleHistory", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("RoleChangeHistories")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Member", "OperatorMember")
                        .WithMany("OperatedRoleHistories")
                        .HasForeignKey("OperatorMemberID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CraftDailyCorner.Models.Role", "Role")
                        .WithMany("MemberRoleHistories")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("OperatorMember");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Message", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("Messages")
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.MessageThread", "MessageThread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("MessageThread");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.MessageThread", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.CreatorProfile", "CreatorProfile")
                        .WithMany("MessageThreads")
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("MessageThreads")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatorProfile");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.NotificationEvent", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("NotificationEvents")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.NotificationPreference", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("NotificationPreferences")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Order", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("Orders")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.OrderDetail", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PasswordResetToken", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Payment", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("MethodID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.PaymentStatus", "PaymentStatus")
                        .WithMany("Payments")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("PaymentMethod");

                    b.Navigation("PaymentStatus");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PlatformAnnouncement", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("PlatformAnnouncements")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.PlatformAnnouncementStatus", "PlatformAnnouncementStatus")
                        .WithMany("PlatformAnnouncements")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("PlatformAnnouncementStatus");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PlatformSetting", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.PlatformSettingCategory", "PlatformSettingCategory")
                        .WithMany("PlatformSettings")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("PlatformSettings")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("PlatformSettingCategory");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Portfolio", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.CreatorProfile", "CreatorProfile")
                        .WithMany("Portfolios")
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorProfile");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PortfolioItem", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Portfolio", "Portfolio")
                        .WithMany("PortfolioItems")
                        .HasForeignKey("PortfolioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PostComment", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("PostComments")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.CreatorPost", "CreatorPost")
                        .WithMany("PostComments")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorPost");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PostCommentReport", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.PostComment", "PostComment")
                        .WithMany("PostCommentReports")
                        .HasForeignKey("CommentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("PostCommentReports")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.PostCommentReportStatus", "PostCommentReportStatus")
                        .WithMany("PostCommentReports")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("PostComment");

                    b.Navigation("PostCommentReportStatus");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Privacy", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithOne("Privacy")
                        .HasForeignKey("CraftDailyCorner.Models.Privacy", "MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Product", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.CreatorProfile", "CreatorProfile")
                        .WithMany("Products")
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.ProductStatus", "ProductStatus")
                        .WithMany("Products")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatorProfile");

                    b.Navigation("ProductStatus");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ProductCategory", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ProductImage", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.ProductImageStatus", "ProductImageStatus")
                        .WithMany("ProductImages")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductImageStatus");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ProductReview", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Member", "Member")
                        .WithMany("ProductReviews")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Product", "Product")
                        .WithMany("ProductReviews")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ProductTag", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Product", "Product")
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.Tag", "Tag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Shipment", b =>
                {
                    b.HasOne("CraftDailyCorner.Models.Order", "Order")
                        .WithOne("Shipment")
                        .HasForeignKey("CraftDailyCorner.Models.Shipment", "OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CraftDailyCorner.Models.ShipmentStatus", "ShipmentStatus")
                        .WithMany("Shipments")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ShipmentStatus");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Category", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorApplicationStatus", b =>
                {
                    b.Navigation("CreatorApplications");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorPost", b =>
                {
                    b.Navigation("PostComments");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorPostStatus", b =>
                {
                    b.Navigation("CreatorPosts");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorProfile", b =>
                {
                    b.Navigation("AutoReplyTemplates");

                    b.Navigation("CreatorPosts");

                    b.Navigation("FollowCreators");

                    b.Navigation("MessageThreads");

                    b.Navigation("Portfolios");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.CreatorProfileStatus", b =>
                {
                    b.Navigation("CreatorProfiles");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.HomepageBannerStatus", b =>
                {
                    b.Navigation("HomepageBanners");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Inventory", b =>
                {
                    b.Navigation("InventoryAlerts");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Member", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("CreatorApplications");

                    b.Navigation("CreatorProfile");

                    b.Navigation("FavoriteProducts");

                    b.Navigation("FollowCreators");

                    b.Navigation("HomepageBanners");

                    b.Navigation("MemberRoles");

                    b.Navigation("MessageThreads");

                    b.Navigation("Messages");

                    b.Navigation("NotificationEvents");

                    b.Navigation("NotificationPreferences");

                    b.Navigation("OperatedRoleHistories");

                    b.Navigation("Orders");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("PlatformAnnouncements");

                    b.Navigation("PlatformSettings");

                    b.Navigation("PostCommentReports");

                    b.Navigation("PostComments");

                    b.Navigation("Privacy");

                    b.Navigation("ProductReviews");

                    b.Navigation("ReviewedCreatorApplications");

                    b.Navigation("RoleChangeHistories");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.MemberStatus", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.MessageThread", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payments");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PaymentStatus", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PlatformAnnouncementStatus", b =>
                {
                    b.Navigation("PlatformAnnouncements");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PlatformSettingCategory", b =>
                {
                    b.Navigation("PlatformSettings");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Portfolio", b =>
                {
                    b.Navigation("PortfolioItems");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PostComment", b =>
                {
                    b.Navigation("PostCommentReports");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.PostCommentReportStatus", b =>
                {
                    b.Navigation("PostCommentReports");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("FavoriteProducts");

                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductCategories");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductReviews");

                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ProductImageStatus", b =>
                {
                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ProductStatus", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Role", b =>
                {
                    b.Navigation("MemberRoleHistories");

                    b.Navigation("MemberRoles");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.ShipmentStatus", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("CraftDailyCorner.Models.Tag", b =>
                {
                    b.Navigation("ProductTags");
                });
#pragma warning restore 612, 618
        }
    }
}
